#!/usr/bin/env node
// Build pipeline for lily-design-system-react-headless.
//
// Two steps, in order:
//
//   1. Generate `index.ts` — the public barrel. Every component in
//      `components/` is re-exported by name, alongside whatever prop
//      types that component declares. The barrel is GENERATED rather
//      than hand-maintained because the catalog is ~491 components and
//      grows: a hand-written list silently omits new components, and an
//      omitted component is invisible to consumers even though its file
//      ships in the tarball.
//
//   2. Bundle to `dist/` with tsup (ESM + .d.ts).
//
// Why this exists at all: until 0.3.0 this package declared
// `"main": "index.js"` and no such file was ever built, so every
// `import ... from "lily-design-system-react-headless"` failed at
// resolution. Nothing caught it because nothing in CI imported the
// package the way a consumer does.
//
// Prop-type names are DISCOVERED from each source file rather than
// assumed to be `${Component}Props`. Two components break that
// assumption — GanttTableTD exports `GanttTableTdProps` and
// GanttTableTH exports `GanttTableThProps` — and guessing the name
// emits a barrel that does not compile.

import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));
const componentsDir = path.join(root, "components");

/** Source files that are components — not tests, not Storybook stories. */
function isComponentSource(name) {
  if (!name.endsWith(".tsx")) return false;
  if (name.endsWith(".test.tsx")) return false;
  if (name.includes(".stories.")) return false;
  return true;
}

const files = fs.readdirSync(componentsDir).filter(isComponentSource).sort();

if (files.length === 0) {
  throw new Error(`No component sources found in ${componentsDir}.`);
}

const lines = [];
const seen = new Map();

for (const file of files) {
  const name = file.slice(0, -".tsx".length);
  const source = fs.readFileSync(path.join(componentsDir, file), "utf8");
  const types = [
    ...source.matchAll(/^export (?:interface|type) ([A-Za-z0-9_]+)/gm),
  ].map((match) => match[1]);

  lines.push(`export { default as ${name} } from "./components/${name}";`);
  if (types.length > 0) {
    lines.push(
      `export type { ${types.join(", ")} } from "./components/${name}";`,
    );
  }

  // A duplicated export name makes the barrel ambiguous, and bundlers
  // resolve that by dropping one side silently. Fail loudly instead.
  for (const exported of [name, ...types]) {
    if (seen.has(exported)) {
      throw new Error(
        `Duplicate export "${exported}": declared by both ` +
          `${seen.get(exported)} and ${file}.`,
      );
    }
    seen.set(exported, file);
  }
}

fs.writeFileSync(
  path.join(root, "index.ts"),
  "// Generated by build.mjs — do not edit by hand.\n" +
    "// Barrel export of every component in the Lily Design System catalog.\n\n" +
    lines.join("\n") +
    "\n",
);
console.log(`generated index.ts (${files.length} components)`);

// Clean first. With `"type": "module"` tsup emits `.js`; without it the
// same command emitted `.mjs`. A dist holding both leaves `exports`
// pointing at whichever pair the last build did not refresh — a stale
// bundle that installs fine and ships month-old code.
fs.rmSync(path.join(root, "dist"), { recursive: true, force: true });

execFileSync(
  "npx",
  [
    "tsup",
    "index.ts",
    "--format", "esm",
    "--dts",
    "--out-dir", "dist",
    "--external", "react",
    "--external", "react-dom",
  ],
  { cwd: root, stdio: "inherit" },
);

// `files` in package.json ships only `dist/`, so an empty or missing
// bundle would publish a package that installs and exports nothing —
// the same class of failure as the missing index.js this replaces.
for (const artifact of ["index.js", "index.d.ts"]) {
  const file = path.join(root, "dist", artifact);
  if (!fs.existsSync(file) || fs.statSync(file).size === 0) {
    throw new Error(`expected a non-empty dist/${artifact} after build.`);
  }
}
console.log("build ok");
